interactions:
- request:
    body: !!python/object/new:_io.BytesIO
      state: !!python/tuple
      - !!binary |
        VGhpcyBpcyB0ZXN0IGZpbGUgMS4K
      - 0
      - null
    headers:
      Authorization:
      - !!binary |
        QVdTIDo2ZkJ2My8xZ2JvZFA3QlJ5WXdzVlpra2trT0k9
      Content-Length: ['21']
      Content-MD5:
      - !!binary |
        N2lRVERpeUNBQi9xUEJaZi9XQzVsUT09
      Date:
      - !!binary |
        TW9uLCAxMCBKdWwgMjAxNyAyMDowNjowMiBHTVQ=
      Expect:
      - !!binary |
        MTAwLWNvbnRpbnVl
      User-Agent:
      - !!binary |
        Qm90bzMvMS40LjQgUHl0aG9uLzMuNi4xIERhcndpbi8xNi42LjAgQm90b2NvcmUvMS41LjU1
    method: PUT
    uri: https://mitodl-repository-test.s3.amazonaws.com/58efd696eb761d78b82c545d/test_file_1.txt
  response:
    body: {string: '<?xml version="1.0" encoding="UTF-8"?>

        <Error><Code>InvalidAccessKeyId</Code><Message>The AWS Access Key Id you provided
        does not exist in our records.</Message><AWSAccessKeyId></AWSAccessKeyId><RequestId>AF68AA1EE1AB3BA3</RequestId><HostId>3nlaBTdsehe3aJaoiMXuocpYV0e9+SRlMHJEhkYvVpZsylyViKGWZUiwzndVmKE0uPekqenufko=</HostId></Error>'}
    headers:
      Connection: [close]
      Content-Type: [application/xml]
      Date: ['Mon, 10 Jul 2017 20:06:02 GMT']
      Server: [AmazonS3]
      x-amz-id-2: [3nlaBTdsehe3aJaoiMXuocpYV0e9+SRlMHJEhkYvVpZsylyViKGWZUiwzndVmKE0uPekqenufko=]
      x-amz-request-id: [AF68AA1EE1AB3BA3]
    status: {code: 403, message: Forbidden}
version: 1
